# start of Meshtastic configure yaml
config:
  device:
    buzzerGpio: 46
  display:
    autoScreenCarouselSecs: 15
  lora:
    region: US
  position:
    gpsMode: ENABLED
    rxGpio: 48
    txGpio: 47
module_config:
  externalNotification:
    active: true
    alertBell: true
    alertBellBuzzer: true
    alertBellVibra: true
    alertMessage: true
    alertMessageBuzzer: true
    alertMessageVibra: true
    enabled: true
    outputBuzzer: 46
    outputVibra: 45
    usePwm: true
